import { motion } from 'framer-motion'
import { Award, TrendingUp, Target, FileText, Download } from 'lucide-react'

const ResultSummary = ({ results }) => {
  const { ats_score: score, matched_skills = [], missing_skills = [], suggestions = [] } = results || {}
  
  const getScoreLevel = (score) => {
    if (score >= 80) return { label: 'Excellent', color: 'text-green-600', bg: 'bg-green-100' }
    if (score >= 60) return { label: 'Good', color: 'text-blue-600', bg: 'bg-blue-100' }
    if (score >= 40) return { label: 'Fair', color: 'text-amber-600', bg: 'bg-amber-100' }
    return { label: 'Needs Work', color: 'text-red-600', bg: 'bg-red-100' }
  }

  const scoreLevel = getScoreLevel(score)

  const handleDownload = () => {
    const report = `
AI Resume Analysis Report
========================
Generated: ${new Date().toLocaleString()}

ATS COMPATIBILITY SCORE: ${score}%
Rating: ${scoreLevel.label}

SKILLS ANALYSIS
---------------
Matched Skills (${matched_skills.length}):
${matched_skills.map(s => `  ✓ ${s}`).join('\n')}

Missing Skills (${missing_skills.length}):
${missing_skills.map(s => `  ✗ ${s}`).join('\n')}

IMPROVEMENT SUGGESTIONS
-----------------------
${suggestions.map((s, i) => `${i + 1}. Original: ${s.original}\n   Improved: ${s.suggestion}`).join('\n\n')}

---
Generated by AI Resume Analyzer
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'resume-analysis-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-br from-indigo-600 to-purple-700 rounded-2xl p-6 text-white mb-6"
    >
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold">Analysis Complete</h2>
          <p className="text-indigo-200 mt-1">Here's how your resume matches the job</p>
        </div>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors text-sm"
          aria-label="Download analysis report"
        >
          <Download className="w-4 h-4" aria-hidden="true" />
          Download Report
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {/* ATS Score */}
        <div className="bg-white/10 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <Award className="w-5 h-5 text-indigo-200" aria-hidden="true" />
            <span className="text-sm text-indigo-200">ATS Score</span>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-bold">{score}%</span>
            <span className={`text-xs px-2 py-0.5 rounded ${scoreLevel.bg} ${scoreLevel.color}`}>
              {scoreLevel.label}
            </span>
          </div>
        </div>

        {/* Skills Match */}
        <div className="bg-white/10 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <Target className="w-5 h-5 text-indigo-200" aria-hidden="true" />
            <span className="text-sm text-indigo-200">Skills Match</span>
          </div>
          <div className="flex items-baseline gap-1">
            <span className="text-3xl font-bold">{matched_skills.length}</span>
            <span className="text-indigo-200">/ {matched_skills.length + missing_skills.length}</span>
          </div>
        </div>

        {/* Missing Skills */}
        <div className="bg-white/10 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-5 h-5 text-indigo-200" aria-hidden="true" />
            <span className="text-sm text-indigo-200">To Improve</span>
          </div>
          <div className="flex items-baseline gap-1">
            <span className="text-3xl font-bold">{missing_skills.length}</span>
            <span className="text-indigo-200">skills</span>
          </div>
        </div>

        {/* Suggestions */}
        <div className="bg-white/10 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="w-5 h-5 text-indigo-200" aria-hidden="true" />
            <span className="text-sm text-indigo-200">Suggestions</span>
          </div>
          <div className="flex items-baseline gap-1">
            <span className="text-3xl font-bold">{suggestions.length}</span>
            <span className="text-indigo-200">tips</span>
          </div>
        </div>
      </div>

      {/* Quick Tip */}
      <div className="mt-4 p-3 bg-white/10 rounded-lg">
        <p className="text-sm text-indigo-100">
          💡 <strong>Quick Tip:</strong>{' '}
          {score >= 80 
            ? "Great job! Your resume is well-optimized for this role."
            : score >= 60
            ? "Add the missing skills to your resume if you have experience with them."
            : "Focus on incorporating more keywords from the job description."}
        </p>
      </div>
    </motion.div>
  )
}

export default ResultSummary
